### ISSUE TITLE
disable badges for taskotron (bot users)

### ISSUE THREAD

**Issue by kparal** [fedora-infra/fedbadges#46]
Taskotron is  [getting badges](https://badges.fedoraproject.org/user/taskotron), and I'm getting notifications for that. Can we stop that? :-)

I think taskotron is marked as a bot account in FAS. Let's stop awarding badges to bot accounts?

**Comment by ralphbean** [comment]
Sure :p  We have a banned list in the config I think...

**Comment by ralphbean** [comment]
Should be fixed by c81f57e.  Rolling it out now.

**Comment by kparal** [comment]
Thanks!
