### ISSUE TITLE
Development badges not being awarded

### ISSUE THREAD

**Issue by nmilosev** [fedora-infra/fedbadges#52]
A quick question: what is the mechanism for awarding these types of issues (kodi/bodhi etc.):

https://badges.fedoraproject.org/badge/if-you-build-it...-koji-success-i

I started packaging recently, so I wonder when does the script? run.

Thanks! :)

I opened an issue also here: https://pagure.io/Fedora-Badges/issue/525

**Comment by bexelbie** [comment]
This appears to be fixed.  Can we close this?

**Comment by nmilosev** [comment]
@bexelbie forgot about this sorry, my issue was an isolated case and now everything is fixed I believe. Can close!

**Comment by justwheel** [comment]
Closing issue :clapper:
