### ISSUE TITLE
Any reason not to use Pagure?

### ISSUE THREAD

**Issue by Jibec** [fedora-infra/fedbadges#57]
Hi, I was wondering if there is any reason not to use Pagure for what looks like a fedora-internal project?

It's a little bit confusing to have some of it on Pagure, some of it on Github. Maybe it's just time consuming?

anyway, I had to ask 😙

**Comment by sayanchowdhury** [comment]
Github `fedora-infra` still holds most of the infra project. The newer projects are created in Pagure.
When fedorahosted went offline, we migrated the badges assets and the issues repo to Pagure.

**Comment by bexelbie** [comment]
It'd be great if we could set this up to be mirrored to GH from pagure ...

**Comment by cverna** [comment]
I am going to close this issue, since I don't think this will lead anywhere. Please feel free to reopen if you disagree.
