### ISSUE TITLE
Replace fedmsg with fedora-messaging

### ISSUE THREAD

**Issue by cverna** [fedora-infra/fedbadges#65]
We need to replace fedmsg with fedora-messaging, I started some initial work on my [fork](https://github.com/cverna/fedbadges/tree/fedora-messaging) but for now there is no good way to replace `fedmsg.meta.msg2usernames` for that we need applications using fedora-messaging to start publishing a schema.

We need to wait for this to happen before replacing fedmsg with fedora-messaging.

**Comment by Darshnadas** [comment]
hey, @cverna Is this issue still being worked?
